### ISSUE TITLE
the extraction code of the Pretrained Models

### ISSUE THREAD

**Issue by LJIAl** [weihaox/Multi-Modal-CelebA-HQ#10]
hello
Thank you for your work. About pretrained models of AttnGAN, ControlGAN, DMGAN, DFGAN, and ManiGAN, I haven't seen the extraction code of the download link, could you please provide it to me?

**Comment by weihaox** [comment]
All these links have been updated. Please check them again.

**Comment by LJIAl** [comment]
> All these links have been updated. Please check them again.

thank you very much
