### ISSUE TITLE
Where to get the post-processing code?

### ISSUE THREAD

**Issue by TiankaiHang** [weihaox/Multi-Modal-CelebA-HQ#12]
Hi,

As noted in README.md,

**Note:** Upon request, the download links of raw data and annotations have been removed from this repo. Please redirect to their original site for the raw data and email me for the post-processing scripts.

Thanks

**Comment by weihaox** [comment]
Please find the [required information](https://github.com/IIGROUP/MM-CelebA-HQ-Dataset#text) in the updated README.md
