### ISSUE TITLE
Upload 'caption.pickle' file

### ISSUE THREAD

**Issue by Kerry-zzx** [weihaox/Multi-Modal-CelebA-HQ#13]
Dear author, thanks for share your code and dataset. Would you mind sharing the caption.pickle file of DFGAN and AttnGAN? Since I got a different result when using the pre-processing code of DFGAN to process the dataset. Thanks a lot,

**Comment by Kerry-zzx** [comment]
If you don't upload the 'caption.pickle' file, the pre-trained weight of DFGAN, DMGAN and AttnGAN may be not useful!!

**Comment by weihaox** [comment]
Sorry for the delayed response. I am unable to provide the requested caption.pickle file. This file can be generated automatically during the training process. If you do not find the pre-trained models useful, you can easily train them yourself with the dataset, which is a straightforward process.

**Comment by weihaox** [comment]
I just found the 'caption.pickle' file from #4.

> [This function](https://github.com/mrlibw/ControlGAN/blob/master/code/datasets.py#L226) loads `captions.pickle` from `data_dir` if it exists. If not, it will build such dictionary from scratch. You can use [this](https://github.com/IIGROUP/Multi-Modal-CelebA-HQ-Dataset/files/6631926/captions.pickle.zip) pickle file I shared and put it in `data_dir`.
