### ISSUE TITLE
Please send me the code for create_caption.py

### ISSUE THREAD

**Issue by Codernob** [weihaox/Multi-Modal-CelebA-HQ#17]
I have requested the create_caption.py file a while ago. Still I haven't received any response. I am working on a project where this script is quite necessary. The deadline is due in a few months. I am under immense pressure to complete the project. Please provide the script.

**Comment by Codernob** [comment]
I have received the code, so I'm closing this issue.

**Comment by fortunechen** [comment]
Could you please share this file with me?
