### ISSUE TITLE
sketch

### ISSUE THREAD

**Issue by SHIJILIANG01** [weihaox/Multi-Modal-CelebA-HQ#19]

**Comment by SHIJILIANG01** [comment]
[create_sketch.py](https://github.com/IIGROUP/MM-CelebA-HQ-Dataset/blob/main/create_sketch.py)
Hello, can this py file generate a sketch directly from the original RGB image?

**Comment by SHIJILIANG01** [comment]
usage: creat_sketch.py [-h] {GAN,MSE,PENCIL1),PENCIL(2} use_cuda data_path save_path
creat_sketch.py: error: unrecognized arguments: --modelname --use_cude --data_path --save_path

**Comment by weihaox** [comment]
Yes, this script generates sketches directly from RGB images. From the error, it looks like the command and parameters you provided contain some typos. Please check and re-enter them.

**Comment by SHIJILIANG01** [comment]
![image](https://github.com/IIGROUP/MM-CelebA-HQ-Dataset/assets/129710581/4d2a7f95-5d41-497c-a3f4-52c45be2c7e0)
![image](https://github.com/IIGROUP/MM-CelebA-HQ-Dataset/assets/129710581/eb151bf8-de82-4b7a-90e2-c78596bb8b5c)
Hello, when I run it, I get this error? How to solve this problem

**Comment by SHIJILIANG01** [comment]
This error indicates that the MD5 checksum of the downloaded model_gan.t7 file does not match the expected one

**Comment by weihaox** [comment]
It seems the downloaded pretrained model is corrupted. Could you try downloading the pretrained models manually?

**Comment by SHIJILIANG01** [comment]
![image](https://github.com/IIGROUP/MM-CelebA-HQ-Dataset/assets/129710581/ec8a40b0-9682-4641-8e4e-3901b8720425)
Yes, I've tried downloading the pre-trained model manually, but I still get this error.

**Comment by weihaox** [comment]
Then please comment [L107-L111](https://github.com/IIGROUP/MM-CelebA-HQ-Dataset/blob/main/create_sketch.py#L107-L111). We use [sketch_simplification](https://github.com/bobbens/sketch_simplification) for sketches. Please refer to their repo. Besides, you could also try the sketch simplification methods proposed recently.

**Comment by SHIJILIANG01** [comment]
Okay, thank you for your help.
