### ISSUE TITLE
image captions tags

### ISSUE THREAD

**Issue by ethan0531** [weihaox/Multi-Modal-CelebA-HQ#2]
Hello, I'd like to ask if there are image captions tags in this dataset. I didn't see them in the downloaded image.

**Comment by weihaox** [comment]
Please download the captions from [text](https://drive.google.com/drive/folders/1ydS2O80rxIU0XtxWzmEI0XDKWEUN4ksI).
![image](https://user-images.githubusercontent.com/54136324/120054991-e91aa700-c065-11eb-9777-083192057851.png)

**Comment by ethan0531** [comment]
ok, thanks!
