### ISSUE TITLE
Is it convenient to provide the code for generating text with PCFG

### ISSUE THREAD

**Issue by jinjiujiujin** [weihaox/Multi-Modal-CelebA-HQ#3]
Hello, I recently tried to study how to automatically generate text according to attributes. I saw that you used PCFG to automatically generate text, so I looked up the materials but still didn't know how to use PCFG to generate text, so I would like to ask if it is convenient for you to provide code.

**Comment by weihaox** [comment]
You can refer to [this paper](https://arxiv.org/pdf/2005.04909.pdf) for more details. They provided a table of how to use PCFG to generate captions. The easiest way is to use if-elses for such tasks. 
<img width="435" alt="截屏2021-06-08 下午3 30 06" src="https://user-images.githubusercontent.com/54136324/121142298-6ae0b080-c86e-11eb-9e38-3bb6fdd215f7.png">

**Comment by jinjiujiujin** [comment]
thank you very much!

**Comment by Crane-YU** [comment]
> You can refer to [this paper](https://arxiv.org/pdf/2005.04909.pdf) for more details. They provided a table of how to use PCFG to generate captions. The easiest way is to use if-elses for such tasks. <img alt="截屏2021-06-08 下午3 30 06" width="435" src="https://user-images.githubusercontent.com/54136324/121142298-6ae0b080-c86e-11eb-9e38-3bb6fdd215f7.png">

Hi @weihaox, 
Thx for the great work. I'm currently generating my own textual description of images following the grammar rule as u mentioned here. I am curious about what **pn** stands for since it is not mentioned in the paper.
Hope u can address this.
