### ISSUE TITLE
The problem of using the pre-trained model of ControlGAN

### ISSUE THREAD

**Issue by cookie-ke** [weihaox/Multi-Modal-CelebA-HQ#4]
Thanks a lot for publishing such amazing datasets.
I had some problems using the pre-training model. The text read from the dataset includes "end". In the pre-training model, there were only 64, and the dimensions did not match.  Could you tell me how to solve it? 
![image](https://user-images.githubusercontent.com/56613566/121136764-952f6f80-c868-11eb-8bb9-7d8c4b0f82dd.png)

**Comment by weihaox** [comment]
For ControlGAN, they first convert captions into index (ixtoword and wordtoix). Those fed into the text encoder are the indexes not the words. If you want to generate images from texts using the pretrained model of ControlGAN, I think it's OK to leave it and just follow the instructions of their codes.

**Comment by cookie-ke** [comment]
Actually, I want to train the ControlGAN by myself. So I don't know how can I change the code and use the face dataset.

**Comment by weihaox** [comment]
You don't have to change the codes. Just change the .yml file.

**Comment by cookie-ke** [comment]
Thanks a lot!!!
![image](https://user-images.githubusercontent.com/56613566/121143078-3a4d4680-c86f-11eb-9ba9-91c48d665c97.png)
This is the folder where the data is placed. And the .yml file also is changed.
![image](https://user-images.githubusercontent.com/56613566/121143282-784a6a80-c86f-11eb-983e-1e92056340fd.png)

**Comment by cookie-ke** [comment]
![image](https://user-images.githubusercontent.com/56613566/121154404-8ac9a180-c879-11eb-9b6d-5a8a55af2757.png)
I don't know if the .yml file setting is right.
But there are also mistakes.
![image](https://user-images.githubusercontent.com/56613566/121154779-d2e8c400-c879-11eb-98fd-3aa54688bb76.png)

**Comment by weihaox** [comment]
To train ControlGAN on face data, I just fix some compatibility issues caused by pytorch. I didn't know if the problem was cause by your previous modifications. My suggestion is to fork another code and try again. [Below](https://github.com/IIGROUP/Multi-Modal-CelebA-HQ-Dataset/files/6615197/Downloads.zip) are yml files that I used. `celeba.yml` should be in path `cfg/DAMSM` and `train_celeba.yml` in `cfg`.

**Comment by cookie-ke** [comment]
sorry. You just upload train_celeba.yml and eval_celeba.yml but you do not upload celeba.yml
![image](https://user-images.githubusercontent.com/56613566/121161566-b3549a00-c87f-11eb-8385-882be1f74cc3.png)

**Comment by weihaox** [comment]
[celeba.yml.zip](https://github.com/IIGROUP/Multi-Modal-CelebA-HQ-Dataset/files/6615552/celeba.yml.zip)

**Comment by cookie-ke** [comment]
![image](https://user-images.githubusercontent.com/56613566/121168744-df731980-c885-11eb-8372-c2e0e813cd54.png)
I can not dowload it

**Comment by weihaox** [comment]
Please right click the link in `To train ControlGAN on face data...` and choose `save as`.

**Comment by cookie-ke** [comment]
Thank you very much! I downloaded the model and code again according to what you said, but he still gave me an error.

![image](https://user-images.githubusercontent.com/56613566/121181394-8b236600-c894-11eb-8d52-e1e2fd333b34.png)

**Comment by weihaox** [comment]
Due to some missing information, I couldn't give you the exact reason. Perhaps you should check if the path of NET_E is correct. If not, please try to debug step by step.

**Comment by cookie-ke** [comment]
I have already debugged step by step and the path of NET_E is correct. I want to know how you put the data set into the folder. I don't know if the way I put right or not.
![image](https://user-images.githubusercontent.com/56613566/121196950-7ac6b780-c8a3-11eb-871a-207b4f17099a.png)
![image](https://user-images.githubusercontent.com/56613566/121197173-aba6ec80-c8a3-11eb-8c9c-c35694f0b369.png)

**Comment by cookie-ke** [comment]
This is my way to put the data into the folder.
![image](https://user-images.githubusercontent.com/56613566/121197438-e27d0280-c8a3-11eb-8088-7e3f1eb89a8a.png)

**Comment by weihaox** [comment]
This is mine. `images` and `text` have no subfolders. The data structure is the same as Bird and COCO used in AttnGAN, ControlGAN, and many others.

<img width="408" alt="截屏2021-06-08 下午9 55 30" src="https://user-images.githubusercontent.com/54136324/121198228-8e265280-c8a4-11eb-8294-550d2e48e9bb.png">

**Comment by cookie-ke** [comment]
Thank you so much for your patience and I will try to change the data location tomorrow . Thanks for your reply again.

**Comment by cookie-ke** [comment]
I changed the data location but I got the same error. Maybe this requirement is a little excessive. Could you please send me the code of your training ControlGan for reference? I promise I won't use the code for any other purpose except research.

**Comment by cookie-ke** [comment]
![image](https://user-images.githubusercontent.com/56613566/121279956-0114e500-c908-11eb-9296-873d6fea698f.png)
I tried to train the pretrain_DAMSM by myself then I found that the size is 65 too. Maybe you change something when you trained ControlGAN?

**Comment by weihaox** [comment]
As far as I can remember, I didn't change the codes except some modifications of compatibility issues. I couldn't download the codes for now as our server broke down due to the air conditioner. Have you ever tried the Bird data and their pretrained model?

**Comment by cookie-ke** [comment]
Yes, I tried the Bird data and their pretrained model and it works. If your server is ready for use, please send me your code. Thank you for replying to me and helping me for such a long time.
![image](https://user-images.githubusercontent.com/56613566/121291035-2c083480-c91a-11eb-8095-011f882ae49d.png)

**Comment by weihaox** [comment]
[Attached](https://github.com/IIGROUP/Multi-Modal-CelebA-HQ-Dataset/files/6628493/code.zip) is the ControlGAN code I used.  

I just compared the two using BeyondCompare and saw no different except commenting some validation codes. The version of Python and Pytorch is 3.7 and 1.7.

**Comment by cookie-ke** [comment]
I found that the code is the same as controlgan , but the result also gets the error. It is really strange. Is it possible that there is a problem with pre-trained model uploading?
![image](https://user-images.githubusercontent.com/56613566/121488623-d0b37080-ca05-11eb-9cd5-1dd484ebff74.png)

**Comment by cookie-ke** [comment]
Mainly because the pre-training time was a little too long since 550 Epochs were needed. So I always want to use the pretrained model that you trained. Thank you very much for replying to me!!!

**Comment by weihaox** [comment]
It worked well for me. The text encoder and image encoder of AttnGAN and ControlGAN are the same. Maybe you should try the pretrained model on AttnGAN?
![image](https://user-images.githubusercontent.com/54136324/121498277-d95c7480-ca0e-11eb-9112-15a70cb8b0be.png)

**Comment by cookie-ke** [comment]
I tried the pretrained model of attngan but it wasn’t work too. It’s really strange. I never changed anything too.

**Comment by cookie-ke** [comment]
I download the dataset and pretrained model again and change the same experiment environment as you but it also doesn't work.
"itxowords" contains these word and the pretrained model only contains 64 words.
Could you please show me the part when you debug the project? when "B_validation" is true. Thank you very much!!!
![image](https://user-images.githubusercontent.com/56613566/121529611-294b3380-ca2f-11eb-8d1d-2a4fe3eccce0.png)
![image](https://user-images.githubusercontent.com/56613566/121529670-3700b900-ca2f-11eb-8f68-4ae8372a018b.png)
![image](https://user-images.githubusercontent.com/56613566/121529711-3ff18a80-ca2f-11eb-8f74-8d25e4c4ad6c.png)
![image](https://user-images.githubusercontent.com/56613566/121529754-4a138900-ca2f-11eb-9df6-5003b6057c7c.png)
![image](https://user-images.githubusercontent.com/56613566/121530073-9d85d700-ca2f-11eb-9c87-da337eb51265.png)
![image](https://user-images.githubusercontent.com/56613566/121530530-1a18b580-ca30-11eb-9a79-4bc7b7b254cd.png)

**Comment by weihaox** [comment]
[This function](https://github.com/mrlibw/ControlGAN/blob/master/code/datasets.py#L226) loads `captions.pickle` from `data_dir` if it exists. If not, it will build such dictionary from scratch. You can use [this](https://github.com/IIGROUP/Multi-Modal-CelebA-HQ-Dataset/files/6631926/captions.pickle.zip) pickle file I shared and put it in `data_dir`.

**Comment by cookie-ke** [comment]
I really appreciate your reply so late! It's true that using it doesn't make the same mistake, but another problem arises. I debug it step by step. The "emb" is 25 but the "cap_lens" is a list which length is 1, so it makes the error occurred.
![image](https://user-images.githubusercontent.com/56613566/121614045-6eec1880-ca90-11eb-9980-2ce97ead2b5f.png)
![image](https://user-images.githubusercontent.com/56613566/121617329-40257080-ca97-11eb-8360-05e1bd7da73f.png)
![image](https://user-images.githubusercontent.com/56613566/121617484-9eeaea00-ca97-11eb-91f5-a27b6ac5f9ef.png)
![image](https://user-images.githubusercontent.com/56613566/121617434-7cf16780-ca97-11eb-82c6-6eff576bde3e.png)

**Comment by weihaox** [comment]
Which version of python and pytorch have you used?

**Comment by cookie-ke** [comment]
![image](https://user-images.githubusercontent.com/56613566/121618100-cd1cf980-ca98-11eb-820d-3019ad475ab8.png)
![image](https://user-images.githubusercontent.com/56613566/121618319-300e9080-ca99-11eb-9651-18d88700e5d1.png)

**Comment by weihaox** [comment]
It's weird that your generated pickle file has different length with mine when we use the same version of python and pytorch.  I don't know why this problem occurred.

**Comment by cookie-ke** [comment]
Yes, I don't know why too. I use the same caption pickle you give but the result is different.

**Comment by cookie-ke** [comment]
Could you please send me all of the data and code to me? Or I can provide the data and code  I used.

**Comment by weihaox** [comment]
I have already shared all the configure files, codes and data. It seems that the pretrained models are successfully loaded. Perhaps you should first correct batch-size.

**Comment by cookie-ke** [comment]
The batch size in the eval_celeba.yml is 1 so I need to change the batch size to 25?

**Comment by cookie-ke** [comment]
Thank you so much for your help!!! I  run the code successfully by changing the batchsize to 25. Because the batchsize is too large and my computer cannot process the project, I run it in colab and  earn the results!
Best wishes!
![image](https://user-images.githubusercontent.com/56613566/121764914-f792b380-cb79-11eb-95d2-06b14333cc86.png)

**Comment by weihaox** [comment]
OK. I closed the issue.
