### ISSUE TITLE
Which face attributes are selected for the dataset?

### ISSUE THREAD

**Issue by cookie-ke** [weihaox/Multi-Modal-CelebA-HQ#5]
Thank you for your work! Which face attributes are selected for the dataset? Can you give me the list? The original data set had 40 attributes

**Comment by weihaox** [comment]
All 40 attributes are used. The list can be found [here](https://drive.google.com/file/d/0B7EVK8r0v71pblRyaVFSWGxPY0U/view?usp=sharing&resourcekey=0-YW2qIuRcWHy_1C2VaRGL3Q).

**Comment by cookie-ke** [comment]
Thanks a lot for your anwsering！ 
Best wishes！
