### ISSUE TITLE
Inverted Codes

### ISSUE THREAD

**Issue by Akila-Ayanthi** [weihaox/Multi-Modal-CelebA-HQ#8]
Hello, 
Could I please know if the inverted codes are available here?

**Comment by weihaox** [comment]
Please check the Baidu Drive [link](https://github.com/IIGROUP/Multi-Modal-CelebA-HQ-Dataset#multi-modal-celeba-hq-dataset-downloads). (multi-modal-celeba-released/dataset/inverted_code/inverted_code.zip).

**Comment by Akila-Ayanthi** [comment]
Thanks for the quick reply.
